In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# reading xlsx file
df_sample=pd.read_excel('/content/Sample Crime Dataset.xlsx')

In [ ]:
df_sample.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)"

In [ ]:
df_sample.shape

(999, 22)

In [ ]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    999 non-null    int64
 1   Case Number           999 non-null    object
 2   Date                  999 non-null    datetime64[ns]
 3   Block                 999 non-null    object
 4   IUCR                  999 non-null    object
 5   Primary Type          999 non-null    object
 6   Description           999 non-null    object
 7   Location Description  997 non-null    object
 8   Arrest                999 non-null    bool
 9   Domestic              999 non-null    bool
 10  Beat                  999 non-null    int64
 11  District              999 non-null    int64
 12  Ward                  998 non-null    float64
 13  Community Area        998 non-null    float64
 14  FBI Code              999 non-null    object
 15  X Coordinate          979 non-null    float64
 16  Y Coordinate          979 non-null    float64
 17  Year                  999 non-null    int64
 18  Updated On            999 non-null    datetime64[ns]
 19  Latitude              979 non-null    float64
 20  Longitude             979 non-null    float64
 21  Location              979 non-null    object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 158.2+ KB

In [ ]:
df_sample.isnull().sum()

ID                       0
Case Number              0
Date                     0
Block                    0
IUCR                     0
Primary Type             0
Description              0
Location Description     2
Arrest                   0
Domestic                 0
Beat                     0
District                 0
Ward                     1
Community Area           1
FBI Code                 0
X Coordinate            20
Y Coordinate            20
Year                     0
Updated On               0
Latitude                20
Longitude               20
Location                20
dtype: int64

In [ ]:
#filling null values for categorical data using mode
df_sample["Location Description"].fillna(df_sample["Location Description"].mode()[0],inplace=True)
df_sample["Ward"].fillna(df_sample["Ward"].mode()[0],inplace=True)
df_sample["Community Area"].fillna(df_sample["Community Area"].mode()[0],inplace=True)

In [ ]:
#replacing null values for locations with "unknown"
df_sample["X Coordinate"].replace(np.nan,"unknown",inplace=True)
df_sample["Y Coordinate"].replace(np.nan,"unknown",inplace=True)
df_sample["Location"].replace(np.nan,"unknown",inplace=True)
df_sample["Latitude"].replace(np.nan,"unknown",inplace=True)
df_sample["Longitude"].replace(np.nan,"unknown",inplace=True)

In [ ]:
df_sample.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [ ]:
df_sample["Primary Type"].unique()

array(['ASSAULT', 'HOMICIDE', 'BURGLARY', 'BATTERY', 'THEFT',
       'CRIMINAL DAMAGE', 'DECEPTIVE PRACTICE', 'CRIMINAL SEXUAL ASSAULT',
       'OFFENSE INVOLVING CHILDREN', 'MOTOR VEHICLE THEFT', 'ROBBERY',
       'SEX OFFENSE', 'OTHER OFFENSE', 'WEAPONS VIOLATION', 'STALKING',
       'CRIMINAL TRESPASS', 'PROSTITUTION', 'ARSON', 'NARCOTICS',
       'KIDNAPPING', 'CONCEALED CARRY LICENSE VIOLATION',
       'INTERFERENCE WITH PUBLIC OFFICER', 'PUBLIC PEACE VIOLATION'],
      dtype=object)

In [ ]:
# seperating date and time from same column
df_sample['Date'] = pd.to_datetime(df_sample['Date'])

df_sample['Crime_Date'] = df_sample['Date'].dt.date
df_sample['Crime_Time'] = df_sample['Date'].dt.time

In [ ]:
# seperating updated date and time from same column
df_sample['Updated On'] = pd.to_datetime(df_sample['Updated On'])

df_sample['Updated_Date'] = df_sample['Updated On'].dt.date
df_sample['Updated_Time'] = df_sample['Updated On'].dt.time

In [ ]:
# droping unnecessary columns
df_sample.drop(['Date'],axis=1,inplace=True)
df_sample.drop(['Updated On'],axis=1,inplace=True)

In [ ]:
df_sample.head()

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,Crime_Date,Crime_Time,Updated_Date,Updated_Time
0,5741943,HN549294,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,...,unknown,unknown,2007,unknown,unknown,unknown,2007-08-25,09:22:18,2015-08-17,15:03:40
1,25953,JE240540,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,...,1141387.0,1913179.0,2021,41.917838,-87.755969,"(41.917838056, -87.755968972)",2021-05-24,15:06:00,2023-11-18,15:39:49
2,26038,JE279849,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,...,1152781.0,1941458.0,2021,41.995219,-87.713355,"(41.995219444, -87.713354912)",2021-06-26,09:24:00,2023-11-18,15:39:49
3,13279676,JG507211,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,...,1162518.0,1925906.0,2023,41.952345,-87.677975,"(41.952345086, -87.677975059)",2023-11-09,07:30:00,2023-11-18,15:39:49
4,13274752,JG501049,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,...,1183071.0,1847869.0,2023,41.737751,-87.604856,"(41.737750767, -87.604855911)",2023-11-12,07:59:00,2023-12-09,15:41:24

In [ ]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    999 non-null    int64
 1   Case Number           999 non-null    object
 2   Block                 999 non-null    object
 3   IUCR                  999 non-null    object
 4   Primary Type          999 non-null    object
 5   Description           999 non-null    object
 6   Location Description  999 non-null    object
 7   Arrest                999 non-null    bool
 8   Domestic              999 non-null    bool
 9   Beat                  999 non-null    int64
 10  District              999 non-null    int64
 11  Ward                  999 non-null    float64
 12  Community Area        999 non-null    float64
 13  FBI Code              999 non-null    object
 14  X Coordinate          999 non-null    object
 15  Y Coordinate          999 non-null    object
 16  Year                  999 non-null    int64
 17  Latitude              999 non-null    object
 18  Longitude             999 non-null    object
 19  Location              999 non-null    object
 20  Crime_Date            999 non-null    object
 21  Crime_Time            999 non-null    object
 22  Updated_Date          999 non-null    object
 23  Updated_Time          999 non-null    object
dtypes: bool(2), float64(2), int64(4), object(16)
memory usage: 173.8+ KB

In [ ]:
# converting the final dataframe to csv file
df_sample.to_csv('SampleData_final.csv',index=False)

# Working on Main Data

In [ ]:
#extracting csv file
df = pd.read_csv('/content/Crimes_-_2001_to_Present.csv')

In [ ]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,08/25/2007 09:22:18 AM,074XX N ROGERS AVE,0560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007.0,08/17/2015 03:03:40 PM,NaN,NaN,NaN
1,25953,JE240540,05/24/2021 03:06:00 PM,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021.0,11/18/2023 03:39:49 PM,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,06/26/2021 09:24:00 AM,062XX N MC CORMICK RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021.0,11/18/2023 03:39:49 PM,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,11/09/2023 07:30:00 AM,019XX W BYRON ST,0620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,05,1162518.0,1925906.0,2023.0,11/18/2023 03:39:49 PM,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,11/12/2023 07:59:00 AM,086XX S COTTAGE GROVE AVE,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023.0,12/09/2023 03:41:24 PM,41.737751,-87.604856,"(41.737750767, -87.604855911)"

In [ ]:
df.shape

(532525, 22)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532525 entries, 0 to 532524
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    532525 non-null  int64
 1   Case Number           532525 non-null  object
 2   Date                  532525 non-null  object
 3   Block                 532525 non-null  object
 4   IUCR                  532525 non-null  object
 5   Primary Type          532525 non-null  object
 6   Description           532525 non-null  object
 7   Location Description  530852 non-null  object
 8   Arrest                532525 non-null  bool
 9   Domestic              532525 non-null  bool
 10  Beat                  532525 non-null  int64
 11  District              532525 non-null  int64
 12  Ward                  213625 non-null  float64
 13  Community Area        214982 non-null  float64
 14  FBI Code              532525 non-null  object
 15  X Coordinate          525720 non-null  float64
 16  Y Coordinate          525720 non-null  float64
 17  Year                  532524 non-null  float64
 18  Updated On            532524 non-null  object
 19  Latitude              525719 non-null  float64
 20  Longitude             525719 non-null  float64
 21  Location              525719 non-null  object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 82.3+ MB

In [ ]:
df.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1673
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    318900
Community Area          317543
FBI Code                     0
X Coordinate              6805
Y Coordinate              6805
Year                         1
Updated On                   1
Latitude                  6806
Longitude                 6806
Location                  6806
dtype: int64

In [ ]:
# replacing null values with "unknown"
df["Location Description"].replace(np.nan,"unknown",inplace=True)
df["Ward"].replace(np.nan,"unknown",inplace=True)
df["Community Area"].replace(np.nan,"unknown",inplace=True)
df["X Coordinate"].replace(np.nan,"unknown",inplace=True)
df["Y Coordinate"].replace(np.nan,"unknown",inplace=True)
df["Location"].replace(np.nan,"unknown",inplace=True)
df["Latitude"].replace(np.nan,"unknown",inplace=True)
df["Longitude"].replace(np.nan,"unknown",inplace=True)

In [ ]:
#seperating Date and Time
df['Date'] = pd.to_datetime(df['Date'])

df['Crime_Date'] = df['Date'].dt.date
df['Crime_Time'] = df['Date'].dt.time

In [ ]:
#seperating Updated Date and time
df['Updated On'] = pd.to_datetime(df['Updated On'])

df['Updated_Date'] = df['Updated On'].dt.date
df['Updated_Time'] = df['Updated On'].dt.time

<ipython-input-24-e475706e7a23>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Updated On'] = pd.to_datetime(df['Updated On'])

In [ ]:
# Droping unnecessary columns
df.drop(['Date'],axis=1,inplace=True)
df.drop(['Updated On'],axis=1,inplace=True)

In [ ]:
df.head()

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,Crime_Date,Crime_Time,Updated_Date,Updated_Time
0,5741943,HN549294,074XX N ROGERS AVE,0560,ASSAULT,SIMPLE,OTHER,False,False,2422,...,unknown,unknown,2007.0,unknown,unknown,unknown,2007-08-25,09:22:18,2015-08-17,15:03:40
1,25953,JE240540,020XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,...,1141387.0,1913179.0,2021.0,41.917838,-87.755969,"(41.917838056, -87.755968972)",2021-05-24,15:06:00,2023-11-18,15:39:49
2,26038,JE279849,062XX N MC CORMICK RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,...,1152781.0,1941458.0,2021.0,41.995219,-87.713355,"(41.995219444, -87.713354912)",2021-06-26,09:24:00,2023-11-18,15:39:49
3,13279676,JG507211,019XX W BYRON ST,0620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,...,1162518.0,1925906.0,2023.0,41.952345,-87.677975,"(41.952345086, -87.677975059)",2023-11-09,07:30:00,2023-11-18,15:39:49
4,13274752,JG501049,086XX S COTTAGE GROVE AVE,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,...,1183071.0,1847869.0,2023.0,41.737751,-87.604856,"(41.737750767, -87.604855911)",2023-11-12,07:59:00,2023-12-09,15:41:24

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532525 entries, 0 to 532524
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    532525 non-null  int64
 1   Case Number           532525 non-null  object
 2   Block                 532525 non-null  object
 3   IUCR                  532525 non-null  object
 4   Primary Type          532525 non-null  object
 5   Description           532525 non-null  object
 6   Location Description  532525 non-null  object
 7   Arrest                532525 non-null  bool
 8   Domestic              532525 non-null  bool
 9   Beat                  532525 non-null  int64
 10  District              532525 non-null  int64
 11  Ward                  532525 non-null  object
 12  Community Area        532525 non-null  object
 13  FBI Code              532525 non-null  object
 14  X Coordinate          532525 non-null  object
 15  Y Coordinate          532525 non-null  object
 16  Year                  532524 non-null  float64
 17  Latitude              532525 non-null  object
 18  Longitude             532525 non-null  object
 19  Location              532525 non-null  object
 20  Crime_Date            532525 non-null  object
 21  Crime_Time            532525 non-null  object
 22  Updated_Date          532524 non-null  object
 23  Updated_Time          532524 non-null  object
dtypes: bool(2), float64(1), int64(3), object(18)
memory usage: 90.4+ MB

In [ ]:
#converting the final data frame in to csv file
df.to_csv('MainData_final.csv',index=False)